# Generated by Django 5.2.14 on 2026-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
